apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookthief
---
apiVersion: v1
kind: Service
metadata:
  name: bookthief
spec:
  selector:
    app: bookthief
  ports:
    - protocol: TCP
      port: 14001
      targetPort: 14001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookthief
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookthief
  template:
    metadata:
      labels:
        app: bookthief
    spec:
      serviceAccountName: bookthief
      containers:
        - name: bookthief
          image: addozhang/bookthief:latest
          ports:
            - containerPort: 14001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'consul,prod'
#            - name: SPRING_CLOUD_CONSUL_HOST
#              value: 'consul.default'
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 60
            periodSeconds: 30
