apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstore
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-v2
  labels:
    version: v1
spec:
  selector:
    app: bookstore-v2
    version: v1
  ports:
    - protocol: TCP
      port: 14001
      targetPort: 14001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-v2
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-v2
      version: v1
  template:
    metadata:
      labels:
        app: bookstore-v2
        version: v1
    spec:
      serviceAccountName: bookstore
      containers:
        - name: bookstore-v2
          image: addozhang/bookstore:latest
          ports:
            - containerPort: 14001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'consul,prod'
            - name: IDENTITY
              value: bookstore-v2
#            - name: SPRING_CLOUD_CONSUL_HOST
#              value: 'consul.default'
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 60
            periodSeconds: 30
